/*
 * Copyright 2023 gematik GmbH
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.07.11 at 06:21:54 PM CEST 
//


package oasis.names.tc.ebxml_regrep.xsd.lcm._3;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import oasis.names.tc.ebxml_regrep.xsd.rim._3.AdhocQueryType;
import oasis.names.tc.ebxml_regrep.xsd.rim._3.ObjectRefType;
import oasis.names.tc.ebxml_regrep.xsd.rim._3.SlotListType;
import oasis.names.tc.ebxml_regrep.xsd.rs._3.RegistryRequestType;
import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.cxf.xjc.runtime.JAXBToStringStyle;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{urn:oasis:names:tc:ebxml-regrep:xsd:rs:3.0}RegistryRequestType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0}AdhocQuery"/&gt;
 *         &lt;element name="SourceRegistry" type="{urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0}ObjectRefType"/&gt;
 *         &lt;element name="DestinationRegistry" type="{urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0}ObjectRefType"/&gt;
 *         &lt;element name="OwnerAtSource" type="{urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0}ObjectRefType"/&gt;
 *         &lt;element name="OwnerAtDestination" type="{urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0}ObjectRefType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "adhocQuery",
    "sourceRegistry",
    "destinationRegistry",
    "ownerAtSource",
    "ownerAtDestination"
})
@XmlRootElement(name = "RelocateObjectsRequest")
public class RelocateObjectsRequest
    extends RegistryRequestType
{

    @XmlElement(name = "AdhocQuery", namespace = "urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0", required = true)
    protected AdhocQueryType adhocQuery;
    @XmlElement(name = "SourceRegistry", required = true)
    protected ObjectRefType sourceRegistry;
    @XmlElement(name = "DestinationRegistry", required = true)
    protected ObjectRefType destinationRegistry;
    @XmlElement(name = "OwnerAtSource", required = true)
    protected ObjectRefType ownerAtSource;
    @XmlElement(name = "OwnerAtDestination", required = true)
    protected ObjectRefType ownerAtDestination;

    /**
     * Gets the value of the adhocQuery property.
     * 
     * @return
     *     possible object is
     *     {@link AdhocQueryType }
     *     
     */
    public AdhocQueryType getAdhocQuery() {
        return adhocQuery;
    }

    /**
     * Sets the value of the adhocQuery property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdhocQueryType }
     *     
     */
    public void setAdhocQuery(AdhocQueryType value) {
        this.adhocQuery = value;
    }

    /**
     * Gets the value of the sourceRegistry property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectRefType }
     *     
     */
    public ObjectRefType getSourceRegistry() {
        return sourceRegistry;
    }

    /**
     * Sets the value of the sourceRegistry property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectRefType }
     *     
     */
    public void setSourceRegistry(ObjectRefType value) {
        this.sourceRegistry = value;
    }

    /**
     * Gets the value of the destinationRegistry property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectRefType }
     *     
     */
    public ObjectRefType getDestinationRegistry() {
        return destinationRegistry;
    }

    /**
     * Sets the value of the destinationRegistry property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectRefType }
     *     
     */
    public void setDestinationRegistry(ObjectRefType value) {
        this.destinationRegistry = value;
    }

    /**
     * Gets the value of the ownerAtSource property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectRefType }
     *     
     */
    public ObjectRefType getOwnerAtSource() {
        return ownerAtSource;
    }

    /**
     * Sets the value of the ownerAtSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectRefType }
     *     
     */
    public void setOwnerAtSource(ObjectRefType value) {
        this.ownerAtSource = value;
    }

    /**
     * Gets the value of the ownerAtDestination property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectRefType }
     *     
     */
    public ObjectRefType getOwnerAtDestination() {
        return ownerAtDestination;
    }

    /**
     * Sets the value of the ownerAtDestination property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectRefType }
     *     
     */
    public void setOwnerAtDestination(ObjectRefType value) {
        this.ownerAtDestination = value;
    }

    public RelocateObjectsRequest withAdhocQuery(AdhocQueryType value) {
        setAdhocQuery(value);
        return this;
    }

    public RelocateObjectsRequest withSourceRegistry(ObjectRefType value) {
        setSourceRegistry(value);
        return this;
    }

    public RelocateObjectsRequest withDestinationRegistry(ObjectRefType value) {
        setDestinationRegistry(value);
        return this;
    }

    public RelocateObjectsRequest withOwnerAtSource(ObjectRefType value) {
        setOwnerAtSource(value);
        return this;
    }

    public RelocateObjectsRequest withOwnerAtDestination(ObjectRefType value) {
        setOwnerAtDestination(value);
        return this;
    }

    @Override
    public RelocateObjectsRequest withRequestSlotList(SlotListType value) {
        setRequestSlotList(value);
        return this;
    }

    @Override
    public RelocateObjectsRequest withId(String value) {
        setId(value);
        return this;
    }

    @Override
    public RelocateObjectsRequest withComment(String value) {
        setComment(value);
        return this;
    }

    @Override
    public boolean equals(Object object) {
        if ((object == null)||(this.getClass()!= object.getClass())) {
            return false;
        }
        if (this == object) {
            return true;
        }
        if (!super.equals(object)) {
            return false;
        }
        final RelocateObjectsRequest that = ((RelocateObjectsRequest) object);
        {
            AdhocQueryType leftAdhocQuery;
            leftAdhocQuery = this.getAdhocQuery();
            AdhocQueryType rightAdhocQuery;
            rightAdhocQuery = that.getAdhocQuery();
            if (this.adhocQuery!= null) {
                if (that.adhocQuery!= null) {
                    if (!leftAdhocQuery.equals(rightAdhocQuery)) {
                        return false;
                    }
                } else {
                    return false;
                }
            } else {
                if (that.adhocQuery!= null) {
                    return false;
                }
            }
        }
        {
            ObjectRefType leftSourceRegistry;
            leftSourceRegistry = this.getSourceRegistry();
            ObjectRefType rightSourceRegistry;
            rightSourceRegistry = that.getSourceRegistry();
            if (this.sourceRegistry!= null) {
                if (that.sourceRegistry!= null) {
                    if (!leftSourceRegistry.equals(rightSourceRegistry)) {
                        return false;
                    }
                } else {
                    return false;
                }
            } else {
                if (that.sourceRegistry!= null) {
                    return false;
                }
            }
        }
        {
            ObjectRefType leftDestinationRegistry;
            leftDestinationRegistry = this.getDestinationRegistry();
            ObjectRefType rightDestinationRegistry;
            rightDestinationRegistry = that.getDestinationRegistry();
            if (this.destinationRegistry!= null) {
                if (that.destinationRegistry!= null) {
                    if (!leftDestinationRegistry.equals(rightDestinationRegistry)) {
                        return false;
                    }
                } else {
                    return false;
                }
            } else {
                if (that.destinationRegistry!= null) {
                    return false;
                }
            }
        }
        {
            ObjectRefType leftOwnerAtSource;
            leftOwnerAtSource = this.getOwnerAtSource();
            ObjectRefType rightOwnerAtSource;
            rightOwnerAtSource = that.getOwnerAtSource();
            if (this.ownerAtSource!= null) {
                if (that.ownerAtSource!= null) {
                    if (!leftOwnerAtSource.equals(rightOwnerAtSource)) {
                        return false;
                    }
                } else {
                    return false;
                }
            } else {
                if (that.ownerAtSource!= null) {
                    return false;
                }
            }
        }
        {
            ObjectRefType leftOwnerAtDestination;
            leftOwnerAtDestination = this.getOwnerAtDestination();
            ObjectRefType rightOwnerAtDestination;
            rightOwnerAtDestination = that.getOwnerAtDestination();
            if (this.ownerAtDestination!= null) {
                if (that.ownerAtDestination!= null) {
                    if (!leftOwnerAtDestination.equals(rightOwnerAtDestination)) {
                        return false;
                    }
                } else {
                    return false;
                }
            } else {
                if (that.ownerAtDestination!= null) {
                    return false;
                }
            }
        }
        return true;
    }

    @Override
    public int hashCode() {
        int currentHashCode = 1;
        currentHashCode = ((currentHashCode* 31)+ super.hashCode());
        {
            currentHashCode = (currentHashCode* 31);
            AdhocQueryType theAdhocQuery;
            theAdhocQuery = this.getAdhocQuery();
            if (this.adhocQuery!= null) {
                currentHashCode += theAdhocQuery.hashCode();
            }
        }
        {
            currentHashCode = (currentHashCode* 31);
            ObjectRefType theSourceRegistry;
            theSourceRegistry = this.getSourceRegistry();
            if (this.sourceRegistry!= null) {
                currentHashCode += theSourceRegistry.hashCode();
            }
        }
        {
            currentHashCode = (currentHashCode* 31);
            ObjectRefType theDestinationRegistry;
            theDestinationRegistry = this.getDestinationRegistry();
            if (this.destinationRegistry!= null) {
                currentHashCode += theDestinationRegistry.hashCode();
            }
        }
        {
            currentHashCode = (currentHashCode* 31);
            ObjectRefType theOwnerAtSource;
            theOwnerAtSource = this.getOwnerAtSource();
            if (this.ownerAtSource!= null) {
                currentHashCode += theOwnerAtSource.hashCode();
            }
        }
        {
            currentHashCode = (currentHashCode* 31);
            ObjectRefType theOwnerAtDestination;
            theOwnerAtDestination = this.getOwnerAtDestination();
            if (this.ownerAtDestination!= null) {
                currentHashCode += theOwnerAtDestination.hashCode();
            }
        }
        return currentHashCode;
    }

    /**
     * Generates a String representation of the contents of this type.
     * This is an extension method, produced by the 'ts' xjc plugin
     * 
     */
    @Override
    public String toString() {
        return ToStringBuilder.reflectionToString(this, JAXBToStringStyle.DEFAULT_STYLE);
    }

}
