/*-
 * #%L
 * lib-ihe-xds
 * %%
 * Copyright (C) 2023 - 2025 gematik GmbH
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 
 * *******
 * 
 * For additional notes and disclaimer from gematik and in case of changes
 * by gematik, find details in the "Readme" file.
 * #L%
 */
//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.07.11 at 06:21:54 PM CEST 
//


package ihe.iti.rmd._2017;


import javax.xml.namespace.QName;
import ihe.iti.xds_b._2007.RetrieveDocumentSetRequestType;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ihe.iti.rmd._2017 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RemoveDocumentsRequest_QNAME = new QName("urn:ihe:iti:rmd:2017", "RemoveDocumentsRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ihe.iti.rmd._2017
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link jakarta.xml.bind.JAXBElement }{@code <}{@link ihe.iti.xds_b._2007.RetrieveDocumentSetRequestType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link jakarta.xml.bind.JAXBElement }{@code <}{@link ihe.iti.xds_b._2007.RetrieveDocumentSetRequestType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:ihe:iti:rmd:2017", name = "RemoveDocumentsRequest")
    public JAXBElement<RetrieveDocumentSetRequestType> createRemoveDocumentsRequest(RetrieveDocumentSetRequestType value) {
        return new JAXBElement<RetrieveDocumentSetRequestType>(_RemoveDocumentsRequest_QNAME, RetrieveDocumentSetRequestType.class, null, value);
    }

}
