/*-
 * #%L
 * lib-ihe-xds
 * %%
 * Copyright (C) 2023 - 2025 gematik GmbH
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 
 * *******
 * 
 * For additional notes and disclaimer from gematik and in case of changes
 * by gematik, find details in the "Readme" file.
 * #L%
 */
//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.07.11 at 06:21:54 PM CEST 
//


package oasis.names.tc.ebxml_regrep.xsd.rim._3;


import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;
import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.cxf.xjc.runtime.JAXBToStringStyle;


/**
 * 
 *         ClassificationScheme is the mapping of the same named interface in ebRIM.
 *         It extends RegistryObject.
 *       
 * 
 * <p>Java class for ClassificationSchemeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ClassificationSchemeType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0}RegistryObjectType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0}ClassificationNode" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="isInternal" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="nodeType" use="required" type="{urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0}referenceURI" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ClassificationSchemeType", propOrder = {
    "classificationNode"
})
public class ClassificationSchemeType
    extends RegistryObjectType
{

    @XmlElement(name = "ClassificationNode")
    protected List<ClassificationNodeType> classificationNode;
    @XmlAttribute(name = "isInternal", required = true)
    protected boolean isInternal;
    @XmlAttribute(name = "nodeType", required = true)
    protected String nodeType;

    /**
     * Gets the value of the classificationNode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the classificationNode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getClassificationNode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ClassificationNodeType }
     * 
     * 
     */
    public List<ClassificationNodeType> getClassificationNode() {
        if (classificationNode == null) {
            classificationNode = new ArrayList<ClassificationNodeType>();
        }
        return this.classificationNode;
    }

    /**
     * Gets the value of the isInternal property.
     * 
     */
    public boolean isIsInternal() {
        return isInternal;
    }

    /**
     * Sets the value of the isInternal property.
     * 
     */
    public void setIsInternal(boolean value) {
        this.isInternal = value;
    }

    /**
     * Gets the value of the nodeType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNodeType() {
        return nodeType;
    }

    /**
     * Sets the value of the nodeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNodeType(String value) {
        this.nodeType = value;
    }

    public ClassificationSchemeType withClassificationNode(ClassificationNodeType... values) {
        if (values!= null) {
            for (ClassificationNodeType value: values) {
                getClassificationNode().add(value);
            }
        }
        return this;
    }

    public ClassificationSchemeType withClassificationNode(Collection<ClassificationNodeType> values) {
        if (values!= null) {
            getClassificationNode().addAll(values);
        }
        return this;
    }

    public ClassificationSchemeType withIsInternal(boolean value) {
        setIsInternal(value);
        return this;
    }

    public ClassificationSchemeType withNodeType(String value) {
        setNodeType(value);
        return this;
    }

    @Override
    public ClassificationSchemeType withName(InternationalStringType value) {
        setName(value);
        return this;
    }

    @Override
    public ClassificationSchemeType withDescription(InternationalStringType value) {
        setDescription(value);
        return this;
    }

    @Override
    public ClassificationSchemeType withVersionInfo(VersionInfoType value) {
        setVersionInfo(value);
        return this;
    }

    @Override
    public ClassificationSchemeType withClassification(ClassificationType... values) {
        if (values!= null) {
            for (ClassificationType value: values) {
                getClassification().add(value);
            }
        }
        return this;
    }

    @Override
    public ClassificationSchemeType withClassification(Collection<ClassificationType> values) {
        if (values!= null) {
            getClassification().addAll(values);
        }
        return this;
    }

    @Override
    public ClassificationSchemeType withExternalIdentifier(ExternalIdentifierType... values) {
        if (values!= null) {
            for (ExternalIdentifierType value: values) {
                getExternalIdentifier().add(value);
            }
        }
        return this;
    }

    @Override
    public ClassificationSchemeType withExternalIdentifier(Collection<ExternalIdentifierType> values) {
        if (values!= null) {
            getExternalIdentifier().addAll(values);
        }
        return this;
    }

    @Override
    public ClassificationSchemeType withLid(String value) {
        setLid(value);
        return this;
    }

    @Override
    public ClassificationSchemeType withObjectType(String value) {
        setObjectType(value);
        return this;
    }

    @Override
    public ClassificationSchemeType withStatus(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public ClassificationSchemeType withSlot(SlotType1 ... values) {
        if (values!= null) {
            for (SlotType1 value: values) {
                getSlot().add(value);
            }
        }
        return this;
    }

    @Override
    public ClassificationSchemeType withSlot(Collection<SlotType1> values) {
        if (values!= null) {
            getSlot().addAll(values);
        }
        return this;
    }

    @Override
    public ClassificationSchemeType withId(String value) {
        setId(value);
        return this;
    }

    @Override
    public ClassificationSchemeType withHome(String value) {
        setHome(value);
        return this;
    }

    @Override
    public boolean equals(Object object) {
        if ((object == null)||(this.getClass()!= object.getClass())) {
            return false;
        }
        if (this == object) {
            return true;
        }
        if (!super.equals(object)) {
            return false;
        }
        final ClassificationSchemeType that = ((ClassificationSchemeType) object);
        {
            List<ClassificationNodeType> leftClassificationNode;
            leftClassificationNode = (((this.classificationNode!= null)&&(!this.classificationNode.isEmpty()))?this.getClassificationNode():null);
            List<ClassificationNodeType> rightClassificationNode;
            rightClassificationNode = (((that.classificationNode!= null)&&(!that.classificationNode.isEmpty()))?that.getClassificationNode():null);
            if ((this.classificationNode!= null)&&(!this.classificationNode.isEmpty())) {
                if ((that.classificationNode!= null)&&(!that.classificationNode.isEmpty())) {
                    if (!leftClassificationNode.equals(rightClassificationNode)) {
                        return false;
                    }
                } else {
                    return false;
                }
            } else {
                if ((that.classificationNode!= null)&&(!that.classificationNode.isEmpty())) {
                    return false;
                }
            }
        }
        {
            boolean leftIsInternal;
            leftIsInternal = this.isIsInternal();
            boolean rightIsInternal;
            rightIsInternal = that.isIsInternal();
            if (leftIsInternal!= rightIsInternal) {
                return false;
            }
        }
        {
            String leftNodeType;
            leftNodeType = this.getNodeType();
            String rightNodeType;
            rightNodeType = that.getNodeType();
            if (this.nodeType!= null) {
                if (that.nodeType!= null) {
                    if (!leftNodeType.equals(rightNodeType)) {
                        return false;
                    }
                } else {
                    return false;
                }
            } else {
                if (that.nodeType!= null) {
                    return false;
                }
            }
        }
        return true;
    }

    @Override
    public int hashCode() {
        int currentHashCode = 1;
        currentHashCode = ((currentHashCode* 31)+ super.hashCode());
        {
            currentHashCode = (currentHashCode* 31);
            List<ClassificationNodeType> theClassificationNode;
            theClassificationNode = (((this.classificationNode!= null)&&(!this.classificationNode.isEmpty()))?this.getClassificationNode():null);
            if ((this.classificationNode!= null)&&(!this.classificationNode.isEmpty())) {
                currentHashCode += theClassificationNode.hashCode();
            }
        }
        {
            currentHashCode = (currentHashCode* 31);
            boolean theIsInternal;
            theIsInternal = this.isIsInternal();
            currentHashCode += (theIsInternal? 1231 : 1237);
        }
        {
            currentHashCode = (currentHashCode* 31);
            String theNodeType;
            theNodeType = this.getNodeType();
            if (this.nodeType!= null) {
                currentHashCode += theNodeType.hashCode();
            }
        }
        return currentHashCode;
    }

    /**
     * Generates a String representation of the contents of this type.
     * This is an extension method, produced by the 'ts' xjc plugin
     * 
     */
    @Override
    public String toString() {
        return ToStringBuilder.reflectionToString(this, JAXBToStringStyle.DEFAULT_STYLE);
    }

}
