/*-
 * #%L
 * lib-ihe-xds
 * %%
 * Copyright (C) 2023 - 2026 gematik GmbH
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 
 * *******
 * 
 * For additional notes and disclaimer from gematik and in case of changes
 * by gematik, find details in the "Readme" file.
 * #L%
 */
//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.07.11 at 06:21:54 PM CEST 
//


package oasis.names.tc.ebxml_regrep.xsd.rim._3;


import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;
import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.cxf.xjc.runtime.JAXBToStringStyle;


/**
 * Mapping of the same named interface in ebRIM.
 * 
 * <p>Java class for PersonNameType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PersonNameType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="firstName" type="{urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0}ShortName" /&gt;
 *       &lt;attribute name="middleName" type="{urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0}ShortName" /&gt;
 *       &lt;attribute name="lastName" type="{urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0}ShortName" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PersonNameType")
public class PersonNameType {

    @XmlAttribute(name = "firstName")
    protected String firstName;
    @XmlAttribute(name = "middleName")
    protected String middleName;
    @XmlAttribute(name = "lastName")
    protected String lastName;

    /**
     * Gets the value of the firstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets the value of the firstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstName(String value) {
        this.firstName = value;
    }

    /**
     * Gets the value of the middleName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMiddleName() {
        return middleName;
    }

    /**
     * Sets the value of the middleName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMiddleName(String value) {
        this.middleName = value;
    }

    /**
     * Gets the value of the lastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastName(String value) {
        this.lastName = value;
    }

    public PersonNameType withFirstName(String value) {
        setFirstName(value);
        return this;
    }

    public PersonNameType withMiddleName(String value) {
        setMiddleName(value);
        return this;
    }

    public PersonNameType withLastName(String value) {
        setLastName(value);
        return this;
    }

    @Override
    public boolean equals(Object object) {
        if ((object == null)||(this.getClass()!= object.getClass())) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final PersonNameType that = ((PersonNameType) object);
        {
            String leftFirstName;
            leftFirstName = this.getFirstName();
            String rightFirstName;
            rightFirstName = that.getFirstName();
            if (this.firstName!= null) {
                if (that.firstName!= null) {
                    if (!leftFirstName.equals(rightFirstName)) {
                        return false;
                    }
                } else {
                    return false;
                }
            } else {
                if (that.firstName!= null) {
                    return false;
                }
            }
        }
        {
            String leftMiddleName;
            leftMiddleName = this.getMiddleName();
            String rightMiddleName;
            rightMiddleName = that.getMiddleName();
            if (this.middleName!= null) {
                if (that.middleName!= null) {
                    if (!leftMiddleName.equals(rightMiddleName)) {
                        return false;
                    }
                } else {
                    return false;
                }
            } else {
                if (that.middleName!= null) {
                    return false;
                }
            }
        }
        {
            String leftLastName;
            leftLastName = this.getLastName();
            String rightLastName;
            rightLastName = that.getLastName();
            if (this.lastName!= null) {
                if (that.lastName!= null) {
                    if (!leftLastName.equals(rightLastName)) {
                        return false;
                    }
                } else {
                    return false;
                }
            } else {
                if (that.lastName!= null) {
                    return false;
                }
            }
        }
        return true;
    }

    @Override
    public int hashCode() {
        int currentHashCode = 1;
        {
            currentHashCode = (currentHashCode* 31);
            String theFirstName;
            theFirstName = this.getFirstName();
            if (this.firstName!= null) {
                currentHashCode += theFirstName.hashCode();
            }
        }
        {
            currentHashCode = (currentHashCode* 31);
            String theMiddleName;
            theMiddleName = this.getMiddleName();
            if (this.middleName!= null) {
                currentHashCode += theMiddleName.hashCode();
            }
        }
        {
            currentHashCode = (currentHashCode* 31);
            String theLastName;
            theLastName = this.getLastName();
            if (this.lastName!= null) {
                currentHashCode += theLastName.hashCode();
            }
        }
        return currentHashCode;
    }

    /**
     * Generates a String representation of the contents of this type.
     * This is an extension method, produced by the 'ts' xjc plugin
     * 
     */
    @Override
    public String toString() {
        return ToStringBuilder.reflectionToString(this, JAXBToStringStyle.DEFAULT_STYLE);
    }

}
