/*
 * Copyright 2023 gematik GmbH
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.07.11 at 06:21:54 PM CEST 
//


package oasis.names.tc.ebxml_regrep.xsd.rim._3;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;
import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.cxf.xjc.runtime.JAXBToStringStyle;


/**
 * <p>Java class for ServiceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ServiceType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0}RegistryObjectType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0}ServiceBinding" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ServiceType", propOrder = {
    "serviceBinding"
})
public class ServiceType
    extends RegistryObjectType
{

    @XmlElement(name = "ServiceBinding")
    protected List<ServiceBindingType> serviceBinding;

    /**
     * Gets the value of the serviceBinding property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the serviceBinding property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getServiceBinding().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link oasis.names.tc.ebxml_regrep.xsd.rim._3.ServiceBindingType }
     * 
     * 
     */
    public List<ServiceBindingType> getServiceBinding() {
        if (serviceBinding == null) {
            serviceBinding = new ArrayList<ServiceBindingType>();
        }
        return this.serviceBinding;
    }

    public ServiceType withServiceBinding(ServiceBindingType... values) {
        if (values!= null) {
            for (ServiceBindingType value: values) {
                getServiceBinding().add(value);
            }
        }
        return this;
    }

    public ServiceType withServiceBinding(Collection<ServiceBindingType> values) {
        if (values!= null) {
            getServiceBinding().addAll(values);
        }
        return this;
    }

    @Override
    public ServiceType withName(InternationalStringType value) {
        setName(value);
        return this;
    }

    @Override
    public ServiceType withDescription(InternationalStringType value) {
        setDescription(value);
        return this;
    }

    @Override
    public ServiceType withVersionInfo(VersionInfoType value) {
        setVersionInfo(value);
        return this;
    }

    @Override
    public ServiceType withClassification(ClassificationType... values) {
        if (values!= null) {
            for (ClassificationType value: values) {
                getClassification().add(value);
            }
        }
        return this;
    }

    @Override
    public ServiceType withClassification(Collection<ClassificationType> values) {
        if (values!= null) {
            getClassification().addAll(values);
        }
        return this;
    }

    @Override
    public ServiceType withExternalIdentifier(ExternalIdentifierType... values) {
        if (values!= null) {
            for (ExternalIdentifierType value: values) {
                getExternalIdentifier().add(value);
            }
        }
        return this;
    }

    @Override
    public ServiceType withExternalIdentifier(Collection<ExternalIdentifierType> values) {
        if (values!= null) {
            getExternalIdentifier().addAll(values);
        }
        return this;
    }

    @Override
    public ServiceType withLid(String value) {
        setLid(value);
        return this;
    }

    @Override
    public ServiceType withObjectType(String value) {
        setObjectType(value);
        return this;
    }

    @Override
    public ServiceType withStatus(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public ServiceType withSlot(SlotType1 ... values) {
        if (values!= null) {
            for (SlotType1 value: values) {
                getSlot().add(value);
            }
        }
        return this;
    }

    @Override
    public ServiceType withSlot(Collection<SlotType1> values) {
        if (values!= null) {
            getSlot().addAll(values);
        }
        return this;
    }

    @Override
    public ServiceType withId(String value) {
        setId(value);
        return this;
    }

    @Override
    public ServiceType withHome(String value) {
        setHome(value);
        return this;
    }

    @Override
    public boolean equals(Object object) {
        if ((object == null)||(this.getClass()!= object.getClass())) {
            return false;
        }
        if (this == object) {
            return true;
        }
        if (!super.equals(object)) {
            return false;
        }
        final ServiceType that = ((ServiceType) object);
        {
            List<ServiceBindingType> leftServiceBinding;
            leftServiceBinding = (((this.serviceBinding!= null)&&(!this.serviceBinding.isEmpty()))?this.getServiceBinding():null);
            List<ServiceBindingType> rightServiceBinding;
            rightServiceBinding = (((that.serviceBinding!= null)&&(!that.serviceBinding.isEmpty()))?that.getServiceBinding():null);
            if ((this.serviceBinding!= null)&&(!this.serviceBinding.isEmpty())) {
                if ((that.serviceBinding!= null)&&(!that.serviceBinding.isEmpty())) {
                    if (!leftServiceBinding.equals(rightServiceBinding)) {
                        return false;
                    }
                } else {
                    return false;
                }
            } else {
                if ((that.serviceBinding!= null)&&(!that.serviceBinding.isEmpty())) {
                    return false;
                }
            }
        }
        return true;
    }

    @Override
    public int hashCode() {
        int currentHashCode = 1;
        currentHashCode = ((currentHashCode* 31)+ super.hashCode());
        {
            currentHashCode = (currentHashCode* 31);
            List<ServiceBindingType> theServiceBinding;
            theServiceBinding = (((this.serviceBinding!= null)&&(!this.serviceBinding.isEmpty()))?this.getServiceBinding():null);
            if ((this.serviceBinding!= null)&&(!this.serviceBinding.isEmpty())) {
                currentHashCode += theServiceBinding.hashCode();
            }
        }
        return currentHashCode;
    }

    /**
     * Generates a String representation of the contents of this type.
     * This is an extension method, produced by the 'ts' xjc plugin
     * 
     */
    @Override
    public String toString() {
        return ToStringBuilder.reflectionToString(this, JAXBToStringStyle.DEFAULT_STYLE);
    }

}
