/*-
 * #%L
 * lib-ihe-xds
 * %%
 * Copyright (C) 2023 - 2026 gematik GmbH
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 
 * *******
 * 
 * For additional notes and disclaimer from gematik and in case of changes
 * by gematik, find details in the "Readme" file.
 * #L%
 */
//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.07.11 at 06:21:54 PM CEST 
//


package oasis.names.tc.ebxml_regrep.xsd.rim._3;


import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;
import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.cxf.xjc.runtime.JAXBToStringStyle;


/**
 * TelephoneNumber is the mapping of the same named interface in ebRIM.
 * 
 * <p>Java class for TelephoneNumberType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TelephoneNumberType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="areaCode" type="{urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0}String8" /&gt;
 *       &lt;attribute name="countryCode" type="{urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0}String8" /&gt;
 *       &lt;attribute name="extension" type="{urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0}String8" /&gt;
 *       &lt;attribute name="number" type="{urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0}String16" /&gt;
 *       &lt;attribute name="phoneType" type="{urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0}String32" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TelephoneNumberType")
public class TelephoneNumberType {

    @XmlAttribute(name = "areaCode")
    protected String areaCode;
    @XmlAttribute(name = "countryCode")
    protected String countryCode;
    @XmlAttribute(name = "extension")
    protected String extension;
    @XmlAttribute(name = "number")
    protected String number;
    @XmlAttribute(name = "phoneType")
    protected String phoneType;

    /**
     * Gets the value of the areaCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * Sets the value of the areaCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAreaCode(String value) {
        this.areaCode = value;
    }

    /**
     * Gets the value of the countryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryCode() {
        return countryCode;
    }

    /**
     * Sets the value of the countryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryCode(String value) {
        this.countryCode = value;
    }

    /**
     * Gets the value of the extension property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtension() {
        return extension;
    }

    /**
     * Sets the value of the extension property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtension(String value) {
        this.extension = value;
    }

    /**
     * Gets the value of the number property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumber() {
        return number;
    }

    /**
     * Sets the value of the number property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumber(String value) {
        this.number = value;
    }

    /**
     * Gets the value of the phoneType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhoneType() {
        return phoneType;
    }

    /**
     * Sets the value of the phoneType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhoneType(String value) {
        this.phoneType = value;
    }

    public TelephoneNumberType withAreaCode(String value) {
        setAreaCode(value);
        return this;
    }

    public TelephoneNumberType withCountryCode(String value) {
        setCountryCode(value);
        return this;
    }

    public TelephoneNumberType withExtension(String value) {
        setExtension(value);
        return this;
    }

    public TelephoneNumberType withNumber(String value) {
        setNumber(value);
        return this;
    }

    public TelephoneNumberType withPhoneType(String value) {
        setPhoneType(value);
        return this;
    }

    @Override
    public boolean equals(Object object) {
        if ((object == null)||(this.getClass()!= object.getClass())) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final TelephoneNumberType that = ((TelephoneNumberType) object);
        {
            String leftAreaCode;
            leftAreaCode = this.getAreaCode();
            String rightAreaCode;
            rightAreaCode = that.getAreaCode();
            if (this.areaCode!= null) {
                if (that.areaCode!= null) {
                    if (!leftAreaCode.equals(rightAreaCode)) {
                        return false;
                    }
                } else {
                    return false;
                }
            } else {
                if (that.areaCode!= null) {
                    return false;
                }
            }
        }
        {
            String leftCountryCode;
            leftCountryCode = this.getCountryCode();
            String rightCountryCode;
            rightCountryCode = that.getCountryCode();
            if (this.countryCode!= null) {
                if (that.countryCode!= null) {
                    if (!leftCountryCode.equals(rightCountryCode)) {
                        return false;
                    }
                } else {
                    return false;
                }
            } else {
                if (that.countryCode!= null) {
                    return false;
                }
            }
        }
        {
            String leftExtension;
            leftExtension = this.getExtension();
            String rightExtension;
            rightExtension = that.getExtension();
            if (this.extension!= null) {
                if (that.extension!= null) {
                    if (!leftExtension.equals(rightExtension)) {
                        return false;
                    }
                } else {
                    return false;
                }
            } else {
                if (that.extension!= null) {
                    return false;
                }
            }
        }
        {
            String leftNumber;
            leftNumber = this.getNumber();
            String rightNumber;
            rightNumber = that.getNumber();
            if (this.number!= null) {
                if (that.number!= null) {
                    if (!leftNumber.equals(rightNumber)) {
                        return false;
                    }
                } else {
                    return false;
                }
            } else {
                if (that.number!= null) {
                    return false;
                }
            }
        }
        {
            String leftPhoneType;
            leftPhoneType = this.getPhoneType();
            String rightPhoneType;
            rightPhoneType = that.getPhoneType();
            if (this.phoneType!= null) {
                if (that.phoneType!= null) {
                    if (!leftPhoneType.equals(rightPhoneType)) {
                        return false;
                    }
                } else {
                    return false;
                }
            } else {
                if (that.phoneType!= null) {
                    return false;
                }
            }
        }
        return true;
    }

    @Override
    public int hashCode() {
        int currentHashCode = 1;
        {
            currentHashCode = (currentHashCode* 31);
            String theAreaCode;
            theAreaCode = this.getAreaCode();
            if (this.areaCode!= null) {
                currentHashCode += theAreaCode.hashCode();
            }
        }
        {
            currentHashCode = (currentHashCode* 31);
            String theCountryCode;
            theCountryCode = this.getCountryCode();
            if (this.countryCode!= null) {
                currentHashCode += theCountryCode.hashCode();
            }
        }
        {
            currentHashCode = (currentHashCode* 31);
            String theExtension;
            theExtension = this.getExtension();
            if (this.extension!= null) {
                currentHashCode += theExtension.hashCode();
            }
        }
        {
            currentHashCode = (currentHashCode* 31);
            String theNumber;
            theNumber = this.getNumber();
            if (this.number!= null) {
                currentHashCode += theNumber.hashCode();
            }
        }
        {
            currentHashCode = (currentHashCode* 31);
            String thePhoneType;
            thePhoneType = this.getPhoneType();
            if (this.phoneType!= null) {
                currentHashCode += thePhoneType.hashCode();
            }
        }
        return currentHashCode;
    }

    /**
     * Generates a String representation of the contents of this type.
     * This is an extension method, produced by the 'ts' xjc plugin
     * 
     */
    @Override
    public String toString() {
        return ToStringBuilder.reflectionToString(this, JAXBToStringStyle.DEFAULT_STYLE);
    }

}
